#:kivy 1.0.9

<GateGuardianPlayer>:
    size: 80, 100
    canvas.before: 
        Line:
            width: 6
            rectangle: self.x, self.y, self.width, self.height
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'background.png'
        
            

<Game>:
    player: player
    
    GateGuardianPlayer:
        id: player
        center: self.parent.center
    